/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hydroScalingAPI.modules.swmmCoupling.widgets;

import hydroScalingAPI.modules.swmmCoupling.io.OutletInflowConnectionCsvImporter;
import hydroScalingAPI.modules.swmmCoupling.objects.OutletInflowConnection;
import hydroScalingAPI.modules.swmmCoupling.objects.OutletInlexMixer;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author A. D. L. Zanchetta
 */
public class FlowDataImporterDialog extends javax.swing.JDialog {

    double tempInfilInt, tempHillVel, tempChannelVel;
    
    /**
     * Creates new form flowDataImporterDialog
     */
    public FlowDataImporterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputInpFileButton = new javax.swing.JButton();
        inputInpFileText = new javax.swing.JTextField();
        InputCuencasDirButton = new javax.swing.JButton();
        InputCuencasDirText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        OutputInpFileButton = new javax.swing.JButton();
        OutputInpFileText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RunSimuNotFoundCheck = new javax.swing.JCheckBox();
        NotFoundBasinsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        connectionsList = new javax.swing.JList();
        setConnectionAddOne = new javax.swing.JButton();
        setConnectionDelOne = new javax.swing.JButton();
        setConnectionAddFile = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mixed data"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("SWMM .inp file:");

        inputInpFileButton.setText("Select...");
        inputInpFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputInpFileButtonActionPerformed(evt);
            }
        });

        InputCuencasDirButton.setText("Select...");
        InputCuencasDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCuencasDirButtonActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cuencas output directory:");

        OutputInpFileButton.setText("Select...");
        OutputInpFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputInpFileButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("New .inp file:");

        RunSimuNotFoundCheck.setText("Run simulation for basins not found");
        RunSimuNotFoundCheck.setEnabled(false);

        NotFoundBasinsButton.setText("Parameters");
        NotFoundBasinsButton.setEnabled(false);
        NotFoundBasinsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotFoundBasinsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RunSimuNotFoundCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NotFoundBasinsButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(InputCuencasDirText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputCuencasDirButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputInpFileText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputInpFileButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(OutputInpFileText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OutputInpFileButton))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputInpFileButton)
                    .addComponent(inputInpFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCuencasDirButton)
                    .addComponent(InputCuencasDirText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutputInpFileButton)
                    .addComponent(OutputInpFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RunSimuNotFoundCheck)
                    .addComponent(NotFoundBasinsButton)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Auto-conect"));

        jRadioButton1.setText("Select");
        jRadioButton1.setEnabled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("User-defined"));

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Select");

        jScrollPane1.setViewportView(connectionsList);

        setConnectionAddOne.setText("Add connection");
        setConnectionAddOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setConnectionAddOneActionPerformed(evt);
            }
        });

        setConnectionDelOne.setText("Delele connection");
        setConnectionDelOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setConnectionDelOneActionPerformed(evt);
            }
        });

        setConnectionAddFile.setText("Add from file");
        setConnectionAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setConnectionAddFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setConnectionAddFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setConnectionDelOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setConnectionAddOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(setConnectionAddOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setConnectionAddFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setConnectionDelOne)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jButton2.setText("Mix");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void setConnectionAddOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setConnectionAddOneActionPerformed
        AddOutletInflowConnectionDialog addDialog;
        
        addDialog = new AddOutletInflowConnectionDialog(this, true);
        
        addDialog.setVisible(true);
        
    }//GEN-LAST:event_setConnectionAddOneActionPerformed

    private void setConnectionDelOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setConnectionDelOneActionPerformed
        int selectedIndex;
        ListModel tempListModel;
        DefaultListModel defListModel;
        
        selectedIndex = this.connectionsList.getSelectedIndex();
        
        tempListModel = this.connectionsList.getModel();
        if(!(tempListModel instanceof DefaultListModel)){
            return;
        }
        
        defListModel = (DefaultListModel)tempListModel;
        
        if (selectedIndex > -1){
            defListModel.removeElementAt(selectedIndex);
        }
    }//GEN-LAST:event_setConnectionDelOneActionPerformed

    private void inputInpFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputInpFileButtonActionPerformed
        File selectedFile;
        JFileChooser fc;
        int result;
        
        fc = new JFileChooser("/");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle("Source .inp file");
        result = fc.showDialog(this, "Select");
        selectedFile = fc.getSelectedFile();
        
        if ((selectedFile != null) && !selectedFile.isDirectory()){
            this.inputInpFileText.setText(selectedFile.getAbsolutePath());
        } else {
            JOptionPane.showMessageDialog(this, "Must select a file.");
        }
    }//GEN-LAST:event_inputInpFileButtonActionPerformed

    private void InputCuencasDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCuencasDirButtonActionPerformed
        File selectedFile;
        JFileChooser fc;
        int result;
        
        fc = new JFileChooser("/");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setDialogTitle("Source CUENCAS directory file");
        result = fc.showDialog(this, "Select");
        selectedFile = fc.getSelectedFile();
        
        if ((selectedFile != null) && selectedFile.isDirectory()){
            this.InputCuencasDirText.setText(selectedFile.getAbsolutePath());
        } else {
            JOptionPane.showMessageDialog(this, "Must select a file.");
        }
    }//GEN-LAST:event_InputCuencasDirButtonActionPerformed

    private void OutputInpFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputInpFileButtonActionPerformed
        File selectedFile;
        JFileChooser fc;
        int result;
        
        fc = new JFileChooser("/");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle("Source .csv file");
        result = fc.showDialog(this, "Select");
        selectedFile = fc.getSelectedFile();
        
        if ((selectedFile != null) && !selectedFile.isDirectory()){
            this.OutputInpFileText.setText(selectedFile.getAbsolutePath());
        } else {
            JOptionPane.showMessageDialog(this, "Must select a file.");
        }
    }//GEN-LAST:event_OutputInpFileButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<OutletInflowConnection> allConnections;
        File swmmInputFile, swmmOutputFile;
        boolean willRunNotFound;
        File cuencasOutputDir;
        ListModel listMod;
        int total, count;
        
        // retrieving all connection identified
        listMod = this.connectionsList.getModel();
        total = listMod.getSize();
        allConnections = new ArrayList<OutletInflowConnection>();
        count = 0;
        while(count < total){
            allConnections.add((OutletInflowConnection)listMod.getElementAt(count));
            count++;
        }
        
        // get other informations
        cuencasOutputDir = new File(this.InputCuencasDirText.getText());
        swmmInputFile = new File(this.inputInpFileText.getText());
        swmmOutputFile = new File(this.OutputInpFileText.getText());
        willRunNotFound = this.RunSimuNotFoundCheck.isSelected();
        
        OutletInlexMixer.mix(allConnections, 
                             swmmInputFile, 
                             cuencasOutputDir, 
                             swmmOutputFile);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NotFoundBasinsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotFoundBasinsButtonActionPerformed
        FlowDataImporterParamsDialog paramsDialog;
        paramsDialog = new FlowDataImporterParamsDialog(this, 
                                                        true, 
                                                        this.tempInfilInt,
                                                        this.tempHillVel,
                                                        this.tempChannelVel);
        paramsDialog.setVisible(true);
    }//GEN-LAST:event_NotFoundBasinsButtonActionPerformed

    private void setConnectionAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setConnectionAddFileActionPerformed
        ArrayList<OutletInflowConnection> all_connections_from_file;
        Iterator<OutletInflowConnection> all_connections_from_file_it;
        OutletInflowConnection cur_connection;
        File selectedFile;
        JFileChooser fc;
        int result;
        
        fc = new JFileChooser("/");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle("SWMM connection .csv file");
        result = fc.showDialog(this, "Select");
        selectedFile = fc.getSelectedFile();
        
        // TODO - read file line by line
        try{
            all_connections_from_file = OutletInflowConnectionCsvImporter.readCsvFile(selectedFile);
        
            all_connections_from_file_it = all_connections_from_file.iterator();
            System.out.println("Opening " + all_connections_from_file.size() + " connections.");
            while(all_connections_from_file_it.hasNext()){
                cur_connection = all_connections_from_file_it.next();
                this.addConnection(cur_connection);
            }
        } catch (IOException exp) {
            System.out.println("Exception: " + exp.getMessage());
        }
    }//GEN-LAST:event_setConnectionAddFileActionPerformed

    public boolean addConnection(OutletInflowConnection outInflConn_arg){
        DefaultListModel defListModel;
        ListModel tempLModel;
        int xBasin, yBasin;
        
        if(outInflConn_arg == null) return (false);
        
        tempLModel = this.connectionsList.getModel();
        if (!(tempLModel instanceof DefaultListModel)){
            this.connectionsList.setModel(new DefaultListModel());
        }
        
        defListModel = (DefaultListModel)this.connectionsList.getModel();
        defListModel.addElement(outInflConn_arg);
        
        return (true);
    }

    public void setTempInfilInt(double tempInfilInt) {
        this.tempInfilInt = tempInfilInt;
    }

    public void setTempHillVel(double tempHillVel) {
        this.tempHillVel = tempHillVel;
    }

    public void setTempChannelVel(double tempChannelVel) {
        this.tempChannelVel = tempChannelVel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InputCuencasDirButton;
    private javax.swing.JTextField InputCuencasDirText;
    private javax.swing.JButton NotFoundBasinsButton;
    private javax.swing.JButton OutputInpFileButton;
    private javax.swing.JTextField OutputInpFileText;
    private javax.swing.JCheckBox RunSimuNotFoundCheck;
    private javax.swing.JList connectionsList;
    private javax.swing.JButton inputInpFileButton;
    private javax.swing.JTextField inputInpFileText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton setConnectionAddFile;
    private javax.swing.JButton setConnectionAddOne;
    private javax.swing.JButton setConnectionDelOne;
    // End of variables declaration//GEN-END:variables
}
